name: Run WebdriverIO Tests and Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://telnyx.com/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          docker build -t wdio-chrome .
          docker run --rm wdio-chrome

      - name: Install Allure CLI
        run: npm install -D allure-commandline

      - name: Generate Allure Report
        run: |
          npm run allure:generate
          mkdir -p public/allure-report
          mv allure-report/* public/allure-report/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/allure-report
          publish_branch: gh-pages
          force_orphan: true